# Generated by Django 3.1 on 2020-08-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifications',
            name='type',
            field=models.CharField(choices=[('Skills', 'Skills'), ('Education', 'Education'), ('Career', 'Career')], max_length=200),
        ),
    ]
